#include <avr/io.h>
#include <avr/wdt.h>
#include <avr/interrupt.h>
#include <lib/delay.h>
#include <lib/lcd.h>

#define DDR_SPI DDRB
#define DD_MOSI PB5
#define DD_SCK PB7
#define DD_SS PB4
#define DD_MISO PB6

//DODAJ MI SZUKANIE LANCUCHA PO REWIZJI W ZALEZNOSCI OD OSTATNIEJ REWIZJI
//DODAJ ZE P0 i P10 BIOR Z RWIZJI I ZE REWIZJA SIE NIE PALI N A NORMLANEJ JEZDIZE

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//ZMIENNE//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
int OSTATNI_STYCZNIK=3;
int STARY_KIERUNEK=2;
int y=69;
int x=69;
int POSTOPIE=0;
int OPOZNIENIE_STYCZNIKOW=100;
int NUMER4=69;
int OPOZNIENIE_WYSWIETLANIA=0;
int OSTATNIE_PIETRO=69;
int DOJAZD_SPECJALNY=0;

int SZUKANIE_DOL=0;
int SZUKANIE_GORA=0;
int SS=0;

//ZMIENNE DYSPOZYCJI
int  PIETRO_0_DYSPOZYCJA=0;
int  PIETRO_1_DYSPOZYCJA=0;
int  PIETRO_2_DYSPOZYCJA=0;
int  PIETRO_3_DYSPOZYCJA=0;
int  PIETRO_4_DYSPOZYCJA=0;
int  PIETRO_5_DYSPOZYCJA=0;
int  PIETRO_6_DYSPOZYCJA=0;
int  PIETRO_7_DYSPOZYCJA=0;
int  PIETRO_8_DYSPOZYCJA=0;
int  PIETRO_9_DYSPOZYCJA=0;
int PIETRO_10_DYSPOZYCJA=0;
//KONIEC ZMIENNYCH DYSPOZYCJI

//ZMIENNE WEZWAN
int  PIETRO_0_WEZWANIE=0;
int  PIETRO_1_WEZWANIE=0;
int  PIETRO_2_WEZWANIE=0;						
int  PIETRO_3_WEZWANIE=0;						
int  PIETRO_4_WEZWANIE=0;
int  PIETRO_5_WEZWANIE=0;
int  PIETRO_6_WEZWANIE=0;
int  PIETRO_7_WEZWANIE=0;
int  PIETRO_8_WEZWANIE=0;
int  PIETRO_9_WEZWANIE=0;
int PIETRO_10_WEZWANIE=0;
//KONIEC ZMIENNYCH WEZWAN

//ZMIENNE OBWODU BEZPIECZENSTWA
int REWIZJA=0;  						
int BURGERS=0;		
int STOP=0; 									//DODAC OBSLUGE STOPU!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
int OGRANICZNIK=0;								//DODAC ODESLANIE PIETRA!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
int RYGLE=0;									//DODAC ZABEZPIECZENIE PRZESLONEK!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
int KABINA=0;									//^czyli zgubienie lancucha jesli sie nie bedom zgadzac przeslonki
int DRZWI=0;									// dodac przyslamnie odczas postoju  i popraiwic czekanei``6ddddddddddddddddddddddwd
int UKLAD_BEZPIECZENSTWA=0;
//KONIEC ZMIENNYCH OBWODU BEZPIECZENSTWA

//ZMIENNE POLOZENIA
int KIERUNEK=2; //0==DOL 1==GORA 2==STAN_INICJUJACY
int ZGUBIONY_LANCUCH=1;
int PIETRO=69;//69 ma byc
int DOLNY_125=0;
int GORNY_125=0;
int FOTKA_LEWA=0;
int FOTKA_PRAWA=0;
int STARA_FOTKA_LEWA=0;
int STARA_FOTKA_PRAWA=0;
//KONIEC ZMIENNYCH POLOZENIA

//ZMIENNE WYBIERANIA KIERUNKU
int ZADANE_PIETRO=69;
int CZEKANIE=50;
int SZYBKOSC_CZEKANIA=2;
//KONIEC ZMIENNYCH IA KIERUNKU

//ZMIENNE STYCZNIKO
int GORA=0;
int DOL=0;
int SZYBKO=0;
int WOLNO=0;
//KONIEC ZMIENNYCH STYCZNIKOW

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//KONIEC ZMIENNYCH/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//METODY///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//METODY SPI
void SPI_MasterInit(void){DDR_SPI = (1<<DD_MOSI)|(1<<DD_SCK)|(1<<DD_SS);SPCR = (1<<SPE)|(1<<MSTR)|(1<<SPR0)|(1<<SPR1);}
void SPI_MasterTransmit(int cData){SPDR = cData;while(!(SPSR & (1<<SPIF)));}
void SPI_SlaveInit(void){DDR_SPI = (1<<DD_MISO);SPCR = (1<<SPE)|(1<<SPR0)|(1<<SPR1);}
int SPI_SlaveReceive(void){while(!(SPSR & (1<<SPIF)));return SPDR;}
//KONIEC METOD SPI

int STYCZNIKI_STOP(void)
{
	if(PINA&0x01){PORTA=PORTA^0x01;}
	if(PINA&0x02){PORTA=PORTA^0x02;}
	if(PINA&0x04){PORTA=PORTA^0x04;}
	if(PINA&0x08){PORTA=PORTA^0x08;}
	return(0);
}

//1-WG 2-SG 3-SS 4-WD 5-SD
int WOLNO_GORA(void)
{
	STYCZNIKI_STOP();
	OSTATNI_STYCZNIK=1;
	OPOZNIENIE_STYCZNIKOW=100;
	if(RYGLE==1){PORTA=PORTA|0x04;}
	PORTA=PORTA|0x02;

	return(0);
}

int SZYBKO_GORA(void)
{
	STYCZNIKI_STOP();

	if(!(OSTATNI_STYCZNIK==2)&&OPOZNIENIE_STYCZNIKOW==0){
		OPOZNIENIE_STYCZNIKOW=100;
		OSTATNI_STYCZNIK=2;
		if(RYGLE==1&&GORNY_125==0){PORTA=PORTA|0x04;}
		PORTA=PORTA|0x01;
	}

	if(OSTATNI_STYCZNIK==2)
	{
		OPOZNIENIE_STYCZNIKOW=100;
		OSTATNI_STYCZNIK=2;
		if(RYGLE==1&&GORNY_125==0){PORTA=PORTA|0x04;}
		PORTA=PORTA|0x01;
	}

	return(0);
}

//1-WG 2-SG 3-SS 4-WD 5-SD
int WOLNO_DOL(void){
	STYCZNIKI_STOP();
	OSTATNI_STYCZNIK=4;
	OPOZNIENIE_STYCZNIKOW=100;
	if(RYGLE==1){PORTA=PORTA|0x08;}
	PORTA=PORTA|0x02;

	return(0);
}

int SZYBKO_DOL(void)
{
	STYCZNIKI_STOP();

	if(!(OSTATNI_STYCZNIK==5)&&OPOZNIENIE_STYCZNIKOW==0){
		OPOZNIENIE_STYCZNIKOW=100;
		OSTATNI_STYCZNIK=5;
		if(RYGLE==1&&DOLNY_125==0){PORTA=PORTA|0x08;}
		PORTA=PORTA|0x01;
	}

	if(OSTATNI_STYCZNIK==5)
	{
		OPOZNIENIE_STYCZNIKOW=100;
		OSTATNI_STYCZNIK=5;
		if(RYGLE==1&&DOLNY_125==0){PORTA=PORTA|0x08;}
		PORTA=PORTA|0x01;
	}

	return(0);
}

int ODNAJDYWANIE_LANCUCHA(void){

	STYCZNIKI_STOP();

	if(
	PIETRO_0_DYSPOZYCJA+PIETRO_1_DYSPOZYCJA+PIETRO_2_DYSPOZYCJA+
	PIETRO_3_DYSPOZYCJA+PIETRO_4_DYSPOZYCJA+PIETRO_5_DYSPOZYCJA+PIETRO_6_DYSPOZYCJA+
	PIETRO_7_DYSPOZYCJA+PIETRO_8_DYSPOZYCJA+PIETRO_9_DYSPOZYCJA+PIETRO_10_DYSPOZYCJA>0){POSTOPIE=0;}

	if(y==211){SS=0;SZUKANIE_GORA=0;SZUKANIE_DOL=0;STYCZNIKI_STOP();CZEKANIE=50;NUMER4=0;}

	//															 | to dodalem |
	if(UKLAD_BEZPIECZENSTWA==1&&ZGUBIONY_LANCUCH==1&&PIETRO==69&&POSTOPIE==0){

	//z gory to jest &&STOP==0

	//if(y==211){SS=0;SZUKANIE_GORA=0;SZUKANIE_DOL=0;STYCZNIKI_STOP();CZEKANIE=100;NUMER4=0;}
	//if(CZEKANIE==0&&SS==0&&!(y==211))
	if(CZEKANIE==0&&SS==0&&!(y==211))
	{
		SS=1;
		if(PIETRO_10_DYSPOZYCJA==1&&DOLNY_125+GORNY_125==0){SZUKANIE_GORA=1;NUMER4=190;}
		if(PIETRO_10_DYSPOZYCJA==0&&DOLNY_125+GORNY_125==0){SZUKANIE_DOL=1;NUMER4=191;}
		if(GORNY_125==1){SZUKANIE_GORA=1;NUMER4=190;}
		if(DOLNY_125==1){SZUKANIE_DOL=1;NUMER4=191;}
	}

	if(SZUKANIE_DOL==1){
		//SZUKANIE LANCUCHA DOL
		if(DOLNY_125==0)
		{SZYBKO_DOL();}
		if(DOLNY_125==1)
		{WOLNO_DOL();}
		}

		if(SZUKANIE_GORA==1){
		//SZUKANIE LANCUCHA DOL
		if(GORNY_125==0)
		{SZYBKO_GORA();}
		if(GORNY_125==1)
		{WOLNO_GORA();}
		}
	}

	if(SZUKANIE_DOL+SZUKANIE_GORA==0){STYCZNIKI_STOP();}

	//ODNALEZIENIE LANUCHA DOL
	if(DOLNY_125==1&&FOTKA_LEWA+FOTKA_PRAWA==2)
	{if(DOLNY_125==1&&FOTKA_LEWA+FOTKA_PRAWA==2)
	{STYCZNIKI_STOP();CZEKANIE=50;SZUKANIE_DOL=0;SZUKANIE_GORA=0;SS=0;NUMER4=69;}}

	//ODNALEZIENIE LANUCHA GORA
	if(GORNY_125==1&&FOTKA_LEWA+FOTKA_PRAWA==2)
	{if(GORNY_125==1&&FOTKA_LEWA+FOTKA_PRAWA==2)
	{STYCZNIKI_STOP();CZEKANIE=50;SZUKANIE_DOL=0;SZUKANIE_GORA=0;SS=0;NUMER4=69;}}

	//KONIEC ODNAJDYWANIA LANCUCHA
	if(UKLAD_BEZPIECZENSTWA==0){STYCZNIKI_STOP();CZEKANIE=50;}

	return(0);
}

int RESET_WEZWAN_I_DYSPOZYCJI(void)
{
	PIETRO_0_DYSPOZYCJA=0;PIETRO_1_DYSPOZYCJA=0;PIETRO_2_DYSPOZYCJA=0;PIETRO_3_DYSPOZYCJA=0;PIETRO_4_DYSPOZYCJA=0;
	PIETRO_5_DYSPOZYCJA=0;PIETRO_6_DYSPOZYCJA=0;PIETRO_7_DYSPOZYCJA=0;PIETRO_8_DYSPOZYCJA=0;PIETRO_9_DYSPOZYCJA=0;
	PIETRO_10_DYSPOZYCJA=0;
	PIETRO_0_WEZWANIE=0;PIETRO_1_WEZWANIE=0;PIETRO_2_WEZWANIE=0;PIETRO_3_WEZWANIE=0;PIETRO_4_WEZWANIE=0;
	PIETRO_5_WEZWANIE=0;PIETRO_6_WEZWANIE=0;PIETRO_7_WEZWANIE=0;PIETRO_8_WEZWANIE=0;PIETRO_9_WEZWANIE=0;
	PIETRO_10_WEZWANIE=0;

	return(0);
}

int RESET_WEZWAN(void)
{
	PIETRO_0_WEZWANIE=0;
	PIETRO_1_WEZWANIE=0;
	PIETRO_2_WEZWANIE=0;	
	PIETRO_3_WEZWANIE=0;	
	PIETRO_4_WEZWANIE=0;
	PIETRO_5_WEZWANIE=0;
	PIETRO_6_WEZWANIE=0;
	PIETRO_7_WEZWANIE=0;
	PIETRO_8_WEZWANIE=0;
	PIETRO_9_WEZWANIE=0;
	PIETRO_10_WEZWANIE=0;

	return(0);
}

int RESET_DYSPOZYCJI(void)
{
	PIETRO_0_DYSPOZYCJA=0;
	PIETRO_1_DYSPOZYCJA=0;
	PIETRO_2_DYSPOZYCJA=0;	
	PIETRO_3_DYSPOZYCJA=0;	
	PIETRO_4_DYSPOZYCJA=0;
	PIETRO_5_DYSPOZYCJA=0;
	PIETRO_6_DYSPOZYCJA=0;
	PIETRO_7_DYSPOZYCJA=0;
	PIETRO_8_DYSPOZYCJA=0;
	PIETRO_9_DYSPOZYCJA=0;
	PIETRO_10_DYSPOZYCJA=0;

	return(0);
}

int PRZESLANIE_SPI (void){
	czekaj(2);
	if((PINB&0x01)){PORTB=PORTB^0x01;}
	czekaj(2);
	if(REWIZJA==1||STOP==1){NUMER4=169;}
	if(REWIZJA==0&&STOP==0&&NUMER4==169){NUMER4=69;}
	if(NUMER4==190||NUMER4==191){SPI_MasterTransmit(69);}
	if(!(NUMER4==190)&&!(NUMER4==191)){SPI_MasterTransmit(NUMER4);}
	czekaj(2);
	PORTB=PORTB|0x01;
	czekaj(2);
	if((PINB&0x01)){PORTB=PORTB^0x01;}
	czekaj(2);
	x=SPI_SlaveReceive();
	czekaj(2);
	PORTB=PORTB|0x01;
	czekaj(2);
	if(x==201){RESET_WEZWAN();}
	if((PINB&0x02)){PORTB=PORTB^0x02;}
	czekaj(2);
	if(REWIZJA==1||STOP==1){NUMER4=169;}
	if(REWIZJA==0&&STOP==0&&NUMER4==169){NUMER4=69;}
	SPI_MasterTransmit(NUMER4);
	czekaj(2);
	PORTB=PORTB|0x02;
	czekaj(2);
	if((PINB&0x02)){PORTB=PORTB^0x02;}
	czekaj(2);
	y=SPI_SlaveReceive();
	y=y+10;
	czekaj(2);
	PORTB=PORTB|0x02;
	czekaj(2);
	if(y==211)
	{
		RESET_DYSPOZYCJI();
		ZADANE_PIETRO=69;POSTOPIE=1;
	}
	//if(y==10){RESET_DYSPOZYCJI();}
	if(y>10&&y<22)
	{
		if(y==11){PIETRO_0_DYSPOZYCJA=1;}
		if(y==12){PIETRO_1_DYSPOZYCJA=1;}
		if(y==13){PIETRO_2_DYSPOZYCJA=1;}
		if(y==14){PIETRO_3_DYSPOZYCJA=1;}
		if(y==15){PIETRO_4_DYSPOZYCJA=1;}
		if(y==16){PIETRO_5_DYSPOZYCJA=1;}
		if(y==17){PIETRO_6_DYSPOZYCJA=1;}
		if(y==18){PIETRO_7_DYSPOZYCJA=1;}
		if(y==19){PIETRO_8_DYSPOZYCJA=1;}
		if(y==20){PIETRO_9_DYSPOZYCJA=1;}
		if(y==21){PIETRO_10_DYSPOZYCJA=1;}}
		if(x==0){RESET_WEZWAN();}
		if(x>0&&x<12){
		if(x==1){PIETRO_0_WEZWANIE=1;}
		if(x==2){PIETRO_1_WEZWANIE=1;}
		if(x==3){PIETRO_2_WEZWANIE=1;}				
		if(x==4){PIETRO_3_WEZWANIE=1;}					
		if(x==5){PIETRO_4_WEZWANIE=1;}
		if(x==6){PIETRO_5_WEZWANIE=1;}
		if(x==7){PIETRO_6_WEZWANIE=1;}
		if(x==8){PIETRO_7_WEZWANIE=1;}
		if(x==9){PIETRO_8_WEZWANIE=1;}
		if(x==10){PIETRO_9_WEZWANIE=1;}
		if(x==11){PIETRO_10_WEZWANIE=1;}
	}

	return(0);
}

int WYSWIETL(void){
	OPOZNIENIE_WYSWIETLANIA-=1;
	if(OPOZNIENIE_WYSWIETLANIA<1)
	{
		//OGRANICZNIK
		if(PINA &0x10){lcdxy(0,0);pisztekst("O");}
		if(!(PINA &0x10)){lcdxy(0,0);pisztekst(" ");}
		//RYGLE
		if(PINA &0x20){lcdxy(0,1);pisztekst("R");}
		if(!(PINA &0x20)){lcdxy(0,1);pisztekst(" ");}
		//KABINA
		if(PINA &0x40){lcdxy(0,2);pisztekst("K");}
		if(!(PINA &0x40)){lcdxy(0,2);pisztekst(" ");}
		//DRZWI
		if(PINA &0x80){lcdxy(0,3);pisztekst("D");}
		if(!(PINA &0x80)){lcdxy(0,3);pisztekst(" ");}
		//STOP
		if(PIND &0x10){lcdxy(0,4);pisztekst("S");}
		if(!(PIND &0x10)){lcdxy(0,4);pisztekst(" ");}
		//BURGERS
		if(PIND &0x20){lcdxy(0,5);pisztekst("B");}
		if(!(PIND &0x20)){lcdxy(0,5);pisztekst(" ");}
		//FOTKA LEWA
		if(PINC&0x02){lcdxy(0,6);pisztekst("L");}
		if(!(PINC&0x02)){lcdxy(0,6);pisztekst(" ");}
		//FOTKA PRAWA
		if(PIND&0x01){lcdxy(0,7);pisztekst("P");}
		if(!(PIND&0x01)){lcdxy(0,7);pisztekst(" ");}
		//GORNY 125
		if(PIND&0x02){lcdxy(0,8);pisztekst("G");}
		if(!(PIND&0x02)){lcdxy(0,8);pisztekst(" ");}
		//DOLNY 125
		if(PIND &0x04){lcdxy(0,9);pisztekst("D");}
		if(!(PIND &0x04)){lcdxy(0,9);pisztekst(" ");}
		//REWIZJA
		if(PIND &0x40){lcdxy(0,10);pisztekst(" ");}
		if(!(PIND &0x40)){lcdxy(0,10);pisztekst("R");}
		//STYCZNIK SZYBKO
		if(PINA&0x01){lcdxy(0,11);pisztekst("H");}
		if(!(PINA&0x01)){lcdxy(0,11);pisztekst(" ");}
		//STYCZNIK WOLNO
		if(PINA&0x02){lcdxy(0,12);pisztekst("L");}
		if(!(PINA&0x02)){lcdxy(0,12);pisztekst(" ");}
		//STYCZNIK GORA
		if(PINA&0x04){lcdxy(0,13);pisztekst("U");}
		if(!(PINA&0x04)){lcdxy(0,13);pisztekst(" ");}
		//STYCZNIK DOL
		if(PINA&0x08){lcdxy(0,14);pisztekst("N");}
		if(!(PINA&0x08)){lcdxy(0,14);pisztekst(" ");}
		//KEIRUENK
		if(KIERUNEK==0){lcdxy(0,15);pisztekst("D");}
		if(KIERUNEK==1){lcdxy(0,15);pisztekst("G");}
		if(KIERUNEK==2){lcdxy(0,15);pisztekst("-");}
		//WYSWIETLENIE POLOZENIA
		lcdxy(1,0);pisztekst("  ");
		char buffer [8]; 			
		itoa(PIETRO,buffer,10);//USUNAC??	 		
		lcdxy(1,0);					
		pisztekst(buffer); 		
		//WYSWIETLENIE CELU
		lcdxy(1,2);pisztekst("  ");
		char buffer2 [8]; 			
		itoa(ZADANE_PIETRO,buffer2,10);//USUNAC??	 			
		lcdxy(1,2);					
		pisztekst(buffer2); 
		//ZMIENNA OPOZNIENIA
		OPOZNIENIE_WYSWIETLANIA=5;
	}

	return(0);
}

int CZEKAJ(void)
{
	if(OPOZNIENIE_STYCZNIKOW>0){OPOZNIENIE_STYCZNIKOW-=SZYBKOSC_CZEKANIA;}
	if(CZEKANIE>0){CZEKANIE-=SZYBKOSC_CZEKANIA;}

	return(0);
}

int ZRESETUJ_I_WYSLIJ_PIETRO(void)
{
	if(PIETRO==0) {NUMER4=1; PRZESLANIE_SPI();PIETRO_0_DYSPOZYCJA=0; PIETRO_0_WEZWANIE=0 ;NUMER4=0;}
	if(PIETRO==3) {NUMER4=2; PRZESLANIE_SPI();PIETRO_1_DYSPOZYCJA=0; PIETRO_1_WEZWANIE=0 ;NUMER4=0;}
	if(PIETRO==6) {NUMER4=3; PRZESLANIE_SPI();PIETRO_2_DYSPOZYCJA=0; PIETRO_2_WEZWANIE=0 ;NUMER4=0;}
	if(PIETRO==9) {NUMER4=4; PRZESLANIE_SPI();PIETRO_3_DYSPOZYCJA=0; PIETRO_3_WEZWANIE=0 ;NUMER4=0;}
	if(PIETRO==12){NUMER4=5; PRZESLANIE_SPI();PIETRO_4_DYSPOZYCJA=0; PIETRO_4_WEZWANIE=0 ;NUMER4=0;}
	if(PIETRO==15){NUMER4=6; PRZESLANIE_SPI();PIETRO_5_DYSPOZYCJA=0; PIETRO_5_WEZWANIE=0 ;NUMER4=0;}
	if(PIETRO==18){NUMER4=7; PRZESLANIE_SPI();PIETRO_6_DYSPOZYCJA=0; PIETRO_6_WEZWANIE=0 ;NUMER4=0;}
	if(PIETRO==21){NUMER4=8; PRZESLANIE_SPI();PIETRO_7_DYSPOZYCJA=0; PIETRO_7_WEZWANIE=0 ;NUMER4=0;}
	if(PIETRO==24){NUMER4=9; PRZESLANIE_SPI();PIETRO_8_DYSPOZYCJA=0; PIETRO_8_WEZWANIE=0 ;NUMER4=0;}
	if(PIETRO==27){NUMER4=10;PRZESLANIE_SPI();PIETRO_9_DYSPOZYCJA=0; PIETRO_9_WEZWANIE=0 ;NUMER4=0;}
	if(PIETRO==30){NUMER4=11;PRZESLANIE_SPI();PIETRO_10_DYSPOZYCJA=0;PIETRO_10_WEZWANIE=0;NUMER4=0;}

	return(0);
}

int WYBRANIE_DOCELOWEGO_PIETRA(void){

	if(
	PIETRO_0_DYSPOZYCJA+PIETRO_1_DYSPOZYCJA+PIETRO_2_DYSPOZYCJA+
	PIETRO_3_DYSPOZYCJA+PIETRO_4_DYSPOZYCJA+PIETRO_5_DYSPOZYCJA+PIETRO_6_DYSPOZYCJA+
	PIETRO_7_DYSPOZYCJA+PIETRO_8_DYSPOZYCJA+PIETRO_9_DYSPOZYCJA+PIETRO_10_DYSPOZYCJA+

	PIETRO_0_WEZWANIE+PIETRO_1_WEZWANIE+PIETRO_2_WEZWANIE+
	PIETRO_3_WEZWANIE+PIETRO_4_WEZWANIE+PIETRO_5_WEZWANIE+PIETRO_6_WEZWANIE+
	PIETRO_7_WEZWANIE+PIETRO_8_WEZWANIE+PIETRO_9_WEZWANIE+PIETRO_10_WEZWANIE==0

	){KIERUNEK=2;ZADANE_PIETRO=69;CZEKANIE=50;};

	if(ZADANE_PIETRO==PIETRO&&GORA+DOL+SZYBKO+WOLNO==0&&PIETRO!=OSTATNIE_PIETRO){STYCZNIKI_STOP();ZRESETUJ_I_WYSLIJ_PIETRO();
	CZEKANIE=50;OPOZNIENIE_STYCZNIKOW=100;OSTATNIE_PIETRO=PIETRO;DOJAZD_SPECJALNY=0;};

	//DLA POSTOPIA
	if(
	PIETRO_0_DYSPOZYCJA+PIETRO_1_DYSPOZYCJA+PIETRO_2_DYSPOZYCJA+
	PIETRO_3_DYSPOZYCJA+PIETRO_4_DYSPOZYCJA+PIETRO_5_DYSPOZYCJA+PIETRO_6_DYSPOZYCJA+
	PIETRO_7_DYSPOZYCJA+PIETRO_8_DYSPOZYCJA+PIETRO_9_DYSPOZYCJA+PIETRO_10_DYSPOZYCJA>0){POSTOPIE=0;};
	//KONIEC DLA POSTOPIA
	if(!(PIETRO==69)){
	if(CZEKANIE>0&&ZADANE_PIETRO==PIETRO)
	{
		if(PIETRO==0){ 		PIETRO_0_DYSPOZYCJA=0 ; PIETRO_0_WEZWANIE=0 ;ZADANE_PIETRO=69;}
		if(PIETRO==3){ 		PIETRO_1_DYSPOZYCJA=0 ; PIETRO_1_WEZWANIE=0 ;ZADANE_PIETRO=69;}
		if(PIETRO==6){ 		PIETRO_2_DYSPOZYCJA=0 ; PIETRO_2_WEZWANIE=0 ;ZADANE_PIETRO=69;}
		if(PIETRO==9){ 		PIETRO_3_DYSPOZYCJA=0 ; PIETRO_3_WEZWANIE=0 ;ZADANE_PIETRO=69;}
		if(PIETRO==12){		PIETRO_4_DYSPOZYCJA=0 ; PIETRO_4_WEZWANIE=0 ;ZADANE_PIETRO=69;}
		if(PIETRO==15){		PIETRO_5_DYSPOZYCJA=0 ; PIETRO_5_WEZWANIE=0 ;ZADANE_PIETRO=69;}
		if(PIETRO==18){		PIETRO_6_DYSPOZYCJA=0 ; PIETRO_6_WEZWANIE=0 ;ZADANE_PIETRO=69;}
		if(PIETRO==21){		PIETRO_7_DYSPOZYCJA=0 ; PIETRO_7_WEZWANIE=0 ;ZADANE_PIETRO=69;}
		if(PIETRO==24){		PIETRO_8_DYSPOZYCJA=0 ; PIETRO_8_WEZWANIE=0 ;ZADANE_PIETRO=69;}
		if(PIETRO==27){		PIETRO_9_DYSPOZYCJA=0 ; PIETRO_9_WEZWANIE=0 ;ZADANE_PIETRO=69;}
		if(PIETRO==30){		PIETRO_10_DYSPOZYCJA=0;PIETRO_10_WEZWANIE=0 ;ZADANE_PIETRO=69;}
	};

	if(KIERUNEK==2&&DOJAZD_SPECJALNY==0&&PIETRO_0_DYSPOZYCJA+PIETRO_1_DYSPOZYCJA+PIETRO_2_DYSPOZYCJA+
	PIETRO_3_DYSPOZYCJA+PIETRO_4_DYSPOZYCJA+PIETRO_5_DYSPOZYCJA+PIETRO_6_DYSPOZYCJA+
	PIETRO_7_DYSPOZYCJA+PIETRO_8_DYSPOZYCJA+PIETRO_9_DYSPOZYCJA+PIETRO_10_DYSPOZYCJA+

	PIETRO_0_WEZWANIE+PIETRO_1_WEZWANIE+PIETRO_2_WEZWANIE+
	PIETRO_3_WEZWANIE+PIETRO_4_WEZWANIE+PIETRO_5_WEZWANIE+PIETRO_6_WEZWANIE+
	PIETRO_7_WEZWANIE+PIETRO_8_WEZWANIE+PIETRO_9_WEZWANIE+PIETRO_10_WEZWANIE>0)
			{
				if(PIETRO==0||PIETRO==3||PIETRO==6||PIETRO==9||PIETRO==12||PIETRO==15||PIETRO==18||PIETRO==21||PIETRO==24||PIETRO==27||PIETRO==30){
				if(PIETRO_0_DYSPOZYCJA==1||PIETRO_0_WEZWANIE==1){if(PIETRO!=0){ZADANE_PIETRO=0;}}
				if(PIETRO_1_DYSPOZYCJA==1||PIETRO_1_WEZWANIE==1){if(PIETRO!=3){ZADANE_PIETRO=3;}}
				if(PIETRO_2_DYSPOZYCJA==1||PIETRO_2_WEZWANIE==1){if(PIETRO!=6){ZADANE_PIETRO=6;}}
				if(PIETRO_3_DYSPOZYCJA==1||PIETRO_3_WEZWANIE==1){if(PIETRO!=9){ZADANE_PIETRO=9;}}
				if(PIETRO_4_DYSPOZYCJA==1||PIETRO_4_WEZWANIE==1){if(PIETRO!=12){ZADANE_PIETRO=12;}}
				if(PIETRO_5_DYSPOZYCJA==1||PIETRO_5_WEZWANIE==1){if(PIETRO!=15){ZADANE_PIETRO=15;}}
				if(PIETRO_6_DYSPOZYCJA==1||PIETRO_6_WEZWANIE==1){if(PIETRO!=18){ZADANE_PIETRO=18;}}
				if(PIETRO_7_DYSPOZYCJA==1||PIETRO_7_WEZWANIE==1){if(PIETRO!=21){ZADANE_PIETRO=21;}}
				if(PIETRO_8_DYSPOZYCJA==1||PIETRO_8_WEZWANIE==1){if(PIETRO!=24){ZADANE_PIETRO=24;}}
				if(PIETRO_9_DYSPOZYCJA==1||PIETRO_9_WEZWANIE==1){if(PIETRO!=27){ZADANE_PIETRO=27;}}
				if(PIETRO_10_DYSPOZYCJA==1||PIETRO_10_WEZWANIE==1){if(PIETRO!=30){ZADANE_PIETRO=30;}}
			}
		}

	if(ZADANE_PIETRO<PIETRO&&ZADANE_PIETRO<30&&ZADANE_PIETRO>=0&&CZEKANIE==0){KIERUNEK=0;}
		if(KIERUNEK==0&&DOJAZD_SPECJALNY==0)
		{
			if(PIETRO==0||PIETRO==3||PIETRO==6||PIETRO==9||PIETRO==12||PIETRO==15||PIETRO==18||PIETRO==21||PIETRO==24||PIETRO==27||PIETRO==30)
			{
				if(PIETRO_0_DYSPOZYCJA==1||PIETRO_0_WEZWANIE-BURGERS==1){if(PIETRO>0){ZADANE_PIETRO=0;}}
				if(PIETRO_1_DYSPOZYCJA==1||PIETRO_1_WEZWANIE-BURGERS==1){if(PIETRO>3){ZADANE_PIETRO=3;}}
				if(PIETRO_2_DYSPOZYCJA==1||PIETRO_2_WEZWANIE-BURGERS==1){if(PIETRO>6){ZADANE_PIETRO=6;}}
				if(PIETRO_3_DYSPOZYCJA==1||PIETRO_3_WEZWANIE-BURGERS==1){if(PIETRO>9){ZADANE_PIETRO=9;}}///maja byc =??????
				if(PIETRO_4_DYSPOZYCJA==1||PIETRO_4_WEZWANIE-BURGERS==1){if(PIETRO>12){ZADANE_PIETRO=12;}}
				if(PIETRO_5_DYSPOZYCJA==1||PIETRO_5_WEZWANIE-BURGERS==1){if(PIETRO>15){ZADANE_PIETRO=15;}}
				if(PIETRO_6_DYSPOZYCJA==1||PIETRO_6_WEZWANIE-BURGERS==1){if(PIETRO>18){ZADANE_PIETRO=18;}}
				if(PIETRO_7_DYSPOZYCJA==1||PIETRO_7_WEZWANIE-BURGERS==1){if(PIETRO>21){ZADANE_PIETRO=21;}}
				if(PIETRO_8_DYSPOZYCJA==1||PIETRO_8_WEZWANIE-BURGERS==1){if(PIETRO>24){ZADANE_PIETRO=24;}}
				if(PIETRO_9_DYSPOZYCJA==1||PIETRO_9_WEZWANIE-BURGERS==1){if(PIETRO>27){ZADANE_PIETRO=27;}}
				if(PIETRO_10_DYSPOZYCJA==1||PIETRO_10_WEZWANIE-BURGERS==1){if(PIETRO>30){ZADANE_PIETRO=30;}}
				if(ZADANE_PIETRO==69){KIERUNEK=2;}
			}
		}

	if(ZADANE_PIETRO>PIETRO&&ZADANE_PIETRO<=30&&ZADANE_PIETRO>0&&CZEKANIE==0){KIERUNEK=1;}
	if(KIERUNEK==1&&DOJAZD_SPECJALNY==0)
	{
		if(PIETRO_0_DYSPOZYCJA+PIETRO_1_DYSPOZYCJA+PIETRO_2_DYSPOZYCJA+
		PIETRO_3_DYSPOZYCJA+PIETRO_4_DYSPOZYCJA+PIETRO_5_DYSPOZYCJA+PIETRO_6_DYSPOZYCJA+
		PIETRO_7_DYSPOZYCJA+PIETRO_8_DYSPOZYCJA+PIETRO_9_DYSPOZYCJA+PIETRO_10_DYSPOZYCJA+

		PIETRO_0_WEZWANIE+PIETRO_1_WEZWANIE+PIETRO_2_WEZWANIE+
		PIETRO_3_WEZWANIE+PIETRO_4_WEZWANIE+PIETRO_5_WEZWANIE+PIETRO_6_WEZWANIE+
		PIETRO_7_WEZWANIE+PIETRO_8_WEZWANIE+PIETRO_9_WEZWANIE+PIETRO_10_WEZWANIE>0)
		{
			if(PIETRO==0||PIETRO==3||PIETRO==6||PIETRO==9||PIETRO==12||PIETRO==15||PIETRO==18||PIETRO==21||PIETRO==24||PIETRO==27||PIETRO==30)
			{
				if(PIETRO_0_WEZWANIE==1){if(PIETRO<0){ZADANE_PIETRO=0;}}
				if(PIETRO_1_WEZWANIE==1){if(PIETRO<3){ZADANE_PIETRO=3;}}
				if(PIETRO_2_WEZWANIE==1){if(PIETRO<6){ZADANE_PIETRO=6;}}
				if(PIETRO_3_WEZWANIE==1){if(PIETRO<9){ZADANE_PIETRO=9;}}
				if(PIETRO_4_WEZWANIE==1){if(PIETRO<12){ZADANE_PIETRO=12;}}
				if(PIETRO_5_WEZWANIE==1){if(PIETRO<15){ZADANE_PIETRO=15;}}
				if(PIETRO_6_WEZWANIE==1){if(PIETRO<18){ZADANE_PIETRO=18;}}
				if(PIETRO_7_WEZWANIE==1){if(PIETRO<21){ZADANE_PIETRO=21;}}
				if(PIETRO_8_WEZWANIE==1){if(PIETRO<24){ZADANE_PIETRO=24;}}
				if(PIETRO_9_WEZWANIE==1){if(PIETRO<27){ZADANE_PIETRO=27;}}
				if(PIETRO_10_WEZWANIE==1){if(PIETRO<30){ZADANE_PIETRO=30;}}

				if(PIETRO_10_DYSPOZYCJA==1){if(PIETRO<30){ZADANE_PIETRO=30;}}
				if(PIETRO_9_DYSPOZYCJA==1){if(PIETRO<27){ZADANE_PIETRO=27;}}
				if(PIETRO_8_DYSPOZYCJA==1){if(PIETRO<24){ZADANE_PIETRO=24;}}
				if(PIETRO_7_DYSPOZYCJA==1){if(PIETRO<21){ZADANE_PIETRO=21;}}
				if(PIETRO_6_DYSPOZYCJA==1){if(PIETRO<18){ZADANE_PIETRO=18;}}
				if(PIETRO_5_DYSPOZYCJA==1){if(PIETRO<15){ZADANE_PIETRO=15;}}
				if(PIETRO_4_DYSPOZYCJA==1){if(PIETRO<12){ZADANE_PIETRO=12;}}
				if(PIETRO_3_DYSPOZYCJA==1){if(PIETRO<9){ZADANE_PIETRO=9;}}
				if(PIETRO_2_DYSPOZYCJA==1){if(PIETRO<6){ZADANE_PIETRO=6;}}
				if(PIETRO_1_DYSPOZYCJA==1){if(PIETRO<3){ZADANE_PIETRO=3;}}
				if(PIETRO_0_DYSPOZYCJA==1){if(PIETRO<0){ZADANE_PIETRO=0;}}
				if(ZADANE_PIETRO==69){KIERUNEK=2;}
			}
		}

	}

	if(PIETRO==0||PIETRO==3||PIETRO==6||PIETRO==9||PIETRO==12||PIETRO==15||PIETRO==18||PIETRO==21||PIETRO==24||PIETRO==27||PIETRO==30){DOJAZD_SPECJALNY=0;}

	};/////////////////////////////////////////////////////////////////////////////////

	if(ZADANE_PIETRO==69&&KIERUNEK==2)
	{
	if(PIETRO==1||PIETRO==2||PIETRO==4||PIETRO==5||PIETRO==7||PIETRO==8||PIETRO==10||
	PIETRO==11||PIETRO==13||PIETRO==14||PIETRO==16||PIETRO==17||PIETRO==19||PIETRO==20||
	PIETRO==22||PIETRO==23||PIETRO==25||PIETRO==26||PIETRO==28||PIETRO==29)
	{
		DOJAZD_SPECJALNY=1;

		if(STARY_KIERUNEK==0){

		if(PIETRO>0){ZADANE_PIETRO=0;KIERUNEK=0;ZADANE_PIETRO=0;DOJAZD_SPECJALNY=1;}
		if(PIETRO>3){ZADANE_PIETRO=3;KIERUNEK=0;ZADANE_PIETRO=3;DOJAZD_SPECJALNY=1;}
		if(PIETRO>6){ZADANE_PIETRO=6;KIERUNEK=0;ZADANE_PIETRO=6;DOJAZD_SPECJALNY=1;}
		if(PIETRO>9){ZADANE_PIETRO=9;KIERUNEK=0;ZADANE_PIETRO=9;DOJAZD_SPECJALNY=1;}
		if(PIETRO>12){ZADANE_PIETRO=12;KIERUNEK=0;ZADANE_PIETRO=12;DOJAZD_SPECJALNY=1;}
		if(PIETRO>15){ZADANE_PIETRO=15;KIERUNEK=0;ZADANE_PIETRO=15;DOJAZD_SPECJALNY=1;}
		if(PIETRO>18){ZADANE_PIETRO=18;KIERUNEK=0;ZADANE_PIETRO=18;DOJAZD_SPECJALNY=1;}
		if(PIETRO>21){ZADANE_PIETRO=21;KIERUNEK=0;ZADANE_PIETRO=21;DOJAZD_SPECJALNY=1;}

		if(PIETRO>24){ZADANE_PIETRO=24;KIERUNEK=0;ZADANE_PIETRO=24;DOJAZD_SPECJALNY=1;}
		if(PIETRO>27){ZADANE_PIETRO=27;KIERUNEK=0;ZADANE_PIETRO=27;DOJAZD_SPECJALNY=1;}

		if(ZADANE_PIETRO==0) {PIETRO_0_WEZWANIE=1;}
		if(ZADANE_PIETRO==3) {PIETRO_1_WEZWANIE=1;}
		if(ZADANE_PIETRO==6) {PIETRO_2_WEZWANIE=1;}
		if(ZADANE_PIETRO==9) {PIETRO_3_WEZWANIE=1;}
		if(ZADANE_PIETRO==12){PIETRO_4_WEZWANIE=1;}
		if(ZADANE_PIETRO==15){PIETRO_5_WEZWANIE=1;}
		if(ZADANE_PIETRO==18){PIETRO_6_WEZWANIE=1;}
		if(ZADANE_PIETRO==21){PIETRO_7_WEZWANIE=1;}
		if(ZADANE_PIETRO==24){PIETRO_8_WEZWANIE=1;}
		if(ZADANE_PIETRO==27){PIETRO_9_WEZWANIE=1;}
	}

	/////////////////////
	if(STARY_KIERUNEK==1)
	{
		if(PIETRO<30){ZADANE_PIETRO=30;KIERUNEK=1;DOJAZD_SPECJALNY=1;}
		if(PIETRO<27){ZADANE_PIETRO=27;KIERUNEK=1;DOJAZD_SPECJALNY=1;}
		if(PIETRO<24){ZADANE_PIETRO=24;KIERUNEK=1;DOJAZD_SPECJALNY=1;}
		if(PIETRO<21){ZADANE_PIETRO=21;KIERUNEK=1;DOJAZD_SPECJALNY=1;}
		if(PIETRO<18){ZADANE_PIETRO=18;KIERUNEK=1;DOJAZD_SPECJALNY=1;}
		if(PIETRO<15){ZADANE_PIETRO=15;KIERUNEK=1;DOJAZD_SPECJALNY=1;}
		if(PIETRO<12){ZADANE_PIETRO=12;KIERUNEK=1;DOJAZD_SPECJALNY=1;}
		if(PIETRO<9){ZADANE_PIETRO=9;KIERUNEK=1;DOJAZD_SPECJALNY=1;}
		if(PIETRO<6){ZADANE_PIETRO=6;KIERUNEK=1;DOJAZD_SPECJALNY=1;}
		if(PIETRO<3){ZADANE_PIETRO=3;KIERUNEK=1;DOJAZD_SPECJALNY=1;}

		if(ZADANE_PIETRO==3) {PIETRO_1_DYSPOZYCJA=1;}
		if(ZADANE_PIETRO==6) {PIETRO_2_DYSPOZYCJA=1;}
		if(ZADANE_PIETRO==9) {PIETRO_3_DYSPOZYCJA=1;}
		if(ZADANE_PIETRO==12){PIETRO_4_DYSPOZYCJA=1;}
		if(ZADANE_PIETRO==15){PIETRO_5_DYSPOZYCJA=1;}
		if(ZADANE_PIETRO==18){PIETRO_6_DYSPOZYCJA=1;}
		if(ZADANE_PIETRO==21){PIETRO_7_DYSPOZYCJA=1;}
		if(ZADANE_PIETRO==24){PIETRO_8_DYSPOZYCJA=1;}
		if(ZADANE_PIETRO==27){PIETRO_9_DYSPOZYCJA=1;}
		if(ZADANE_PIETRO==30){PIETRO_9_DYSPOZYCJA=1;}
	}

	}
	}

	return(0);
}

int ZLICZANIE_PRZESLONEK(void){
	if(KIERUNEK==1||KIERUNEK==0)
	{
		STARY_KIERUNEK=KIERUNEK;
	}
	if(STARA_FOTKA_LEWA==0&&FOTKA_LEWA==1&&KIERUNEK==1){PIETRO+=1;}
	if(STARA_FOTKA_PRAWA==0&&FOTKA_PRAWA==1&&KIERUNEK==1){PIETRO+=1;}
	if(STARA_FOTKA_LEWA==0&&FOTKA_LEWA==1&&KIERUNEK==0){PIETRO-=1;}
	if(STARA_FOTKA_PRAWA==0&&FOTKA_PRAWA==1&&KIERUNEK==0){PIETRO-=1;}
	//DODAC ZE PRZY KIERUNKU 2 MA ZE STAREGO KIERUNKU ZLICZAC

	if(KIERUNEK==2&&STARA_FOTKA_LEWA==0&&FOTKA_LEWA==1&&STARY_KIERUNEK==1){PIETRO+=1;}
	if(KIERUNEK==2&&STARA_FOTKA_PRAWA==0&&FOTKA_PRAWA==1&&STARY_KIERUNEK==1){PIETRO+=1;}
	if(KIERUNEK==2&&STARA_FOTKA_LEWA==0&&FOTKA_LEWA==1&&STARY_KIERUNEK==0){PIETRO-=1;}
	if(KIERUNEK==2&&STARA_FOTKA_PRAWA==0&&FOTKA_PRAWA==1&&STARY_KIERUNEK==0){PIETRO-=1;}

	STARA_FOTKA_LEWA=FOTKA_LEWA;
	STARA_FOTKA_PRAWA=FOTKA_PRAWA;
	return(0);}

	int SPRAWDZENIE_POLOZENIA_KABINY(void){

	if(DOLNY_125==1&&FOTKA_LEWA+FOTKA_PRAWA==2)
	{
		PIETRO=0;
		if(ZGUBIONY_LANCUCH==1){ZRESETUJ_I_WYSLIJ_PIETRO();czekaj(5);ZRESETUJ_I_WYSLIJ_PIETRO();}
		ZGUBIONY_LANCUCH=0;
	}
	if(GORNY_125==1&&FOTKA_LEWA+FOTKA_PRAWA==2)
	{
		PIETRO=30;
		if(ZGUBIONY_LANCUCH==1){ZRESETUJ_I_WYSLIJ_PIETRO();czekaj(5);ZRESETUJ_I_WYSLIJ_PIETRO();}
		ZGUBIONY_LANCUCH=0;
	}

	return(0);
}

int SPRAWDZENIE_LANCUCHA(void){

	if(PIETRO==0&&DOLNY_125==0&&GORA+DOL+SZYBKO+WOLNO==0){ZGUBIONY_LANCUCH=1;}
	if(PIETRO==30&&GORNY_125==0&&GORA+DOL+SZYBKO+WOLNO==0){ZGUBIONY_LANCUCH=1;}

	if(PIETRO>30||PIETRO<0){ZGUBIONY_LANCUCH=1;PIETRO=69;}

/*
if(PIETRO!=69){
/////////////////////////////////////////////////////////////////////////////////////////////
if(PIETRO==1)
{
if(KIERUNEK==1){if(FOTKA_PRAWA==1){PIETRO=2;}}
}
//////////////////////////////////////////////////////////////////////////////////////////////
if(PIETRO==2||PIETRO==3||PIETRO==4)
{
if(KIERUNEK==1){if(FOTKA_LEWA==1){PIETRO=5;}}
if(KIERUNEK==0){if(FOTKA_LEWA==1){PIETRO=1;}}
}
/////////////////////////////////////////////////////////////////////////////////////////////
if(PIETRO==5||PIETRO==6||PIETRO==7)
{
if(KIERUNEK==1){if(FOTKA_PRAWA==1){PIETRO=8;}}
if(KIERUNEK==0){if(FOTKA_PRAWA==1){PIETRO=4;}}
}
//////////////////////////////////////////////////////////////////////////////////////////////
if(PIETRO==8||PIETRO==9||PIETRO==10)
{
if(KIERUNEK==1){if(FOTKA_LEWA==1){PIETRO=11;}}
if(KIERUNEK==0){if(FOTKA_LEWA==1){PIETRO=7;}}
}
/////////////////////////////////////////////////////////////////////////////////////////////
if(PIETRO==11||PIETRO==12||PIETRO==13)
{
if(KIERUNEK==1){if(FOTKA_PRAWA==1){PIETRO=14;}}
if(KIERUNEK==0){if(FOTKA_PRAWA==1){PIETRO=10;}}
}
//////////////////////////////////////////////////////////////////////////////////////////////
if(PIETRO==14||PIETRO==15||PIETRO==16)
{
if(KIERUNEK==1){if(FOTKA_LEWA==1){PIETRO=17;}}
if(KIERUNEK==0){if(FOTKA_LEWA==1){PIETRO=13;}}
}
/////////////////////////////////////////////////////////////////////////////////////////////
if(PIETRO==17||PIETRO==18||PIETRO==19)
{
if(KIERUNEK==1){if(FOTKA_PRAWA==1){PIETRO=20;}}
if(KIERUNEK==0){if(FOTKA_PRAWA==1){PIETRO=16;}}
}
//////////////////////////////////////////////////////////////////////////////////////////////
if(PIETRO==20||PIETRO==21||PIETRO==22)
{
if(KIERUNEK==1){if(FOTKA_LEWA==1){PIETRO=23;}}
if(KIERUNEK==0){if(FOTKA_LEWA==1){PIETRO=19;}}
}
/////////////////////////////////////////////////////////////////////////////////////////////
if(PIETRO==23||PIETRO==24||PIETRO==25)
{
if(KIERUNEK==1){if(FOTKA_PRAWA==1){PIETRO=26;}}
if(KIERUNEK==0){if(FOTKA_PRAWA==1){PIETRO=22;}}
}
/////////////////////////////////////////////////////////////////////////////////////////////
if(PIETRO==26||PIETRO==27||PIETRO==28)
{
if(KIERUNEK==1){if(FOTKA_LEWA==1){PIETRO=29;}}
if(KIERUNEK==0){if(FOTKA_LEWA==1){PIETRO=25;}}
}
/////////////////////////////////////////////////////////////////////////////////////////////
if(PIETRO==29)
{
if(KIERUNEK==0){if(FOTKA_PRAWA==1){PIETRO=28;}}
}
*/

	if(PIETRO==2||PIETRO==3||PIETRO==4||
	PIETRO==8||PIETRO==9||PIETRO==10||
	PIETRO==14||PIETRO==15||PIETRO==16||
	PIETRO==20||PIETRO==21||PIETRO==22||
	PIETRO==26||PIETRO==27||PIETRO==28)
	{if(FOTKA_LEWA==1){ZGUBIONY_LANCUCH=1;PIETRO=69;ZADANE_PIETRO=69;CZEKANIE=50;}}

	if(PIETRO==1||
	PIETRO==5||PIETRO==6||PIETRO==7||
	PIETRO==11||PIETRO==12||PIETRO==13||
	PIETRO==17||PIETRO==18||PIETRO==19||
	PIETRO==23||PIETRO==24||PIETRO==25||
	PIETRO==29)
	{if(FOTKA_PRAWA==1){ZGUBIONY_LANCUCH=1;PIETRO=69;ZADANE_PIETRO=69;CZEKANIE=50;}}

	return(0);
}

int SPRAWDZENIE_WEJSC_I_WYJSC(void)
{

	//OBSLUGA PRZYCISKOW
	//if(PINA &0x04){PRZYCISK_1=0;}
	//if(PINA &0x08){PRZYCISK_2=0;}
	//if(PIND &0x08){PRZYCISK_3=0;}

	//CZARNA KOSTKA WEJSCIE 1
	if(PINA &0x10){OGRANICZNIK=1;}
	if(!(PINA &0x10)){OGRANICZNIK=0;}
	//CZARNA KOSTKA WEJSCIE 2
	if(PINA &0x20){RYGLE=1;}
	if(!(PINA &0x20)){RYGLE=0;}

	//CZARNA KOSTKA WEJSCIE 4
	if(PINA &0x80){DRZWI=1;}
	if(!(PINA &0x80)){DRZWI=0;}

	//CZARNA KOSTKA WEJSCIE 3
	if(PINA &0x40){KABINA=1;}
	if(!(PINA &0x40)){KABINA=0;}

	//POD EKRANEM WEJSCIE 1
	if(PINC&0x02){FOTKA_LEWA=1;}
	if(!(PINC&0x02)){FOTKA_LEWA=0;}
	//POD EKRANEM WEJSCIE 2
	if(PIND&0x01){FOTKA_PRAWA=1;}
	if(!(PIND&0x01)){FOTKA_PRAWA=0;}
	//POD EKRANEM WEJSCIE 3
	if(PIND&0x02){GORNY_125=1;}
	if(!(PIND&0x02)){GORNY_125=0;}
	//POD EKRANEM WEJSCIE 4
	if(PIND &0x04){DOLNY_125=1;}
	if(!(PIND &0x04)){DOLNY_125=0;}
	//STYCZNIK SZYBKO
	if(PINA&0x01){SZYBKO=1;}
	if(!(PINA&0x01)){SZYBKO=0;}
	//STYCZNIK WOLNO
	if(PINA&0x02){WOLNO=1;}
	if(!(PINA&0x02)){WOLNO=0;}
	//STYCZNIK GORA
	if(PINA&0x04){GORA=1;}
	if(!(PINA&0x04)){GORA=0;}
	//STYCZNIK DOL
	if(PINA&0x08){DOL=1;}
	if(!(PINA&0x08)){DOL=0;}

	//STOP
	if(PIND &0x10){STOP=1;RESET_WEZWAN_I_DYSPOZYCJI();}
	if(!(PIND &0x10)){STOP=0;}

	//BURGERS
	if(PIND &0x20){BURGERS=1;}
	if(!(PIND &0x20)){BURGERS=0;}
	//REWIZJA
	if(PIND &0x40){REWIZJA=0;}
	if(!(PIND &0x40)){REWIZJA=1;}
	if(OGRANICZNIK+KABINA+DRZWI==3){UKLAD_BEZPIECZENSTWA=1;}
	if(!(OGRANICZNIK+KABINA+DRZWI==3)){UKLAD_BEZPIECZENSTWA=0;}

	if(KABINA==0&&DRZWI==1)
	{

		STOP=1;POSTOPIE=1;RESET_WEZWAN_I_DYSPOZYCJI();

	}

	return(0);
}

int ZASTEROWANIE_STYCZNIKOW(void)
{

	if(UKLAD_BEZPIECZENSTWA==1&&ZGUBIONY_LANCUCH==0&&POSTOPIE==0&&y+x!=10)
	{
		if(KIERUNEK==0&&PIETRO>ZADANE_PIETRO+1){STYCZNIKI_STOP();SZYBKO_DOL();}
		if(KIERUNEK==0&&PIETRO==ZADANE_PIETRO+1){STYCZNIKI_STOP();WOLNO_DOL();}
		if(KIERUNEK==1&&PIETRO<ZADANE_PIETRO-1){STYCZNIKI_STOP();SZYBKO_GORA();}
		if(KIERUNEK==1&&PIETRO==ZADANE_PIETRO-1){STYCZNIKI_STOP();WOLNO_GORA();}

		if(KIERUNEK==1)
		{
			if(GORNY_125==1&&FOTKA_LEWA+FOTKA_PRAWA<2){WOLNO_GORA();}
		}
		if(KIERUNEK==0)
		{
			if(DOLNY_125==1&&FOTKA_LEWA+FOTKA_PRAWA<2){WOLNO_DOL();}
		}

	}

	if(KIERUNEK==1)
	{
		if(GORNY_125==1&&FOTKA_LEWA+FOTKA_PRAWA==2){czekaj(50);STYCZNIKI_STOP();}//CZEKAJ JEST ZEBY DOBRZE NAJECHAL NA PRZESLONKI
	}
	if(KIERUNEK==0)
	{
		if(DOLNY_125==1&&FOTKA_LEWA+FOTKA_PRAWA==2){czekaj(50);STYCZNIKI_STOP();}//CZEKAJ JEST ZEBY DOBRZE NAJECHAL NA PRZESLONKI
	}

	if(ZADANE_PIETRO==69){STYCZNIKI_STOP();}
	if(ZADANE_PIETRO==PIETRO&&GORA+DOL+SZYBKO+WOLNO==0){STYCZNIKI_STOP();CZEKANIE=50;OPOZNIENIE_STYCZNIKOW=100;DOJAZD_SPECJALNY=0;}

	if(KIERUNEK==2)
	{
		STYCZNIKI_STOP();
	}

	if(UKLAD_BEZPIECZENSTWA==0){STYCZNIKI_STOP();CZEKANIE=50;}
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	return(0);
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//KONIEC METOD/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//GLOWNY PROGRAM///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
int main(void)
{
	//WYLACZENIE JTAG
	MCUCSR |= (1<<JTD); 
	MCUCSR |= (1<<JTD); 
	//KONIEC WYLACZENIA JTAG
	//USTAWIENIE REHESTROW
	DDRA=0x0f;
	DDRB=0x03;		//0x09
	DDRC=0xfc;		//0xfe
	DDRD=0x00;		//0x00
	//KONIEC USTAWIANIA REESTROW
	//USTAWIENIE PORTOW
	PORTA=0x00;
	PORTB=0x00;
	PORTC=0x00;		//0x00
	PORTD=0x78;		//0x7c
	//KONIEC USTAWIANIA PORTOW
	//INICJALIZACJA LCD I SPLASH
	inicjuj_lcd();
	lcdxy(1,0);pisztekst("                ");
	lcdxy(0,0);pisztekst("                ");
	lcdxy(1,0);pisztekst("x");
	czekaj(100);
	lcdxy(1,0);pisztekst("xx");
	czekaj(100);
	lcdxy(1,0);pisztekst("xxx");
	czekaj(100);
	lcdxy(1,0);pisztekst("                ");
	czekaj(100);
	//KONIEC INCJALIZACJI I SPALSH
	//INICJALIZACJA SPI
	SPI_MasterInit();
	DDRB=DDRB|0x01;
	DDRB=DDRB|0x02;
	//KONIEC INICJALIZACJI SPI
	//POZATEK PETLI
	while(1)
	{

		//rewizja
		if(REWIZJA==1)
		{

			//STYCZNIKI_STOP();

			SS=0;SZUKANIE_GORA=0;SZUKANIE_DOL=0;CZEKANIE=50;

			ZADANE_PIETRO=69;
			RESET_WEZWAN_I_DYSPOZYCJI();
			SPRAWDZENIE_WEJSC_I_WYJSC();

			SPRAWDZENIE_POLOZENIA_KABINY();
			ZLICZANIE_PRZESLONEK();

			SPRAWDZENIE_LANCUCHA();

			PRZESLANIE_SPI();

			if(UKLAD_BEZPIECZENSTWA==1){
			if(y==11&&DOLNY_125==0){WOLNO_DOL();KIERUNEK=0;STARY_KIERUNEK=0;}
			if(y==21&&GORNY_125==0){WOLNO_GORA();KIERUNEK=1;STARY_KIERUNEK=1;}

			if(y==11&&DOLNY_125==1){STYCZNIKI_STOP();}
			if(y==21&&GORNY_125==1){STYCZNIKI_STOP();}

			if(!(y==11)&&!(y==21)){STYCZNIKI_STOP();}
			}

			if(!(y==11)&&!(y==21)){STYCZNIKI_STOP();}
			if(UKLAD_BEZPIECZENSTWA==0){STYCZNIKI_STOP();}

		}

		//szukanie lancucha
		if(ZGUBIONY_LANCUCH==1&&REWIZJA==0)
		{
			STYCZNIKI_STOP();

			SPRAWDZENIE_WEJSC_I_WYJSC();

			SPRAWDZENIE_POLOZENIA_KABINY();

			SPRAWDZENIE_LANCUCHA();
			//TYLKO POZA TESTAMI

			ODNAJDYWANIE_LANCUCHA();
			CZEKAJ();

			PRZESLANIE_SPI();

		}
		//normalna jazda
		if(ZGUBIONY_LANCUCH==0&&REWIZJA==0)
		{
			STYCZNIKI_STOP();
			SPRAWDZENIE_WEJSC_I_WYJSC();

			SPRAWDZENIE_POLOZENIA_KABINY();
			ZLICZANIE_PRZESLONEK();

			SPRAWDZENIE_LANCUCHA();
			//TYLKO POZA TESTAMI

			WYBRANIE_DOCELOWEGO_PIETRA();
			ZASTEROWANIE_STYCZNIKOW();
			CZEKAJ();

			PRZESLANIE_SPI();
		}

		WYSWIETL();
	}
		//KONIEC PETLI
}
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//KONIEC GLOWNEGO PROGRAMU/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////